import re

stat_emojis = {
      "STR": ":muscle:",
      "DEX": ":runner:",
      "CON": ":heart:",
      "INT": ":brain:",
      "POW": ":zap:",
      "APP": ":heart_eyes:",
      "EDU": ":mortar_board:",
      "SIZ": ":bust_in_silhouette:",
      "HP": ":heartpulse:",
      "MP": ":sparkles:",
      "LUCK": ":four_leaf_clover:",
      "SAN": ":scales:",
      "Age": ":birthday:",
      "Residence": ":house:",
      "Occupation": ":briefcase:",
      "Move": ":person_running:",
      "Build": ":restroom:",
      "Damage Bonus": ":mending_heart:",
      "DB": ":mending_heart:",
      "Accounting": ":ledger:",
      "Anthropology": ":earth_americas:",
      "Appraise": ":mag:",
      "Archaeology": ":pick:",
      "Charm": ":heart_decoration:",
      "Photography": ":camera_with_flash:",
      "Art/Craft": ":art:",
      "Climb": ":mountain:",
      "Credit Rating": ":moneybag:",
      "Cthulhu Mythos": ":octopus:",
      "Demolitions": ":boom:",
      "Disguise": ":dress:",
      "Diving": ":diving_mask:",
      "Dodge": ":warning:",
      "Drive Auto": ":blue_car:",
      "Elec. Repair": ":wrench:",
      "Fast Talk": ":pinched_fingers:",
      "Fighting Brawl": ":boxing_glove:",
      "Firearms Handgun": ":gun:",
      "Firearms Rifle/Shotgun": ":gun:",
      "First Aid": ":ambulance:",
      "History": ":scroll:",
      "Intimidate": ":fearful:",
      "Jump": ":athletic_shoe:",
      "Language other": ":globe_with_meridians:",
      "Language own": ":speech_balloon:",
      "Law": ":scales:",
      "Library Use": ":books:",
      "Listen": ":ear:",
      "Locksmith": ":key:",
      "Mech. Repair": ":wrench:",
      "Medicine": ":pill:",
      "Natural World": ":deciduous_tree:",
      "Navigate": ":compass:",
      "Occult": ":crystal_ball:",
      "Persuade": ":speech_balloon:",
      "Pilot": ":airplane:",
      "Psychoanalysis": ":brain:",
      "Psychology": ":brain:",
      "Read Lips": ":lips:",
      "Ride": ":horse_racing:",
      "Science specific": ":microscope:",
      "Sleight of Hand": ":mage:",
      "Spot Hidden": ":eyes:",
      "Stealth": ":footprints:",
      "Survival": ":camping:",
      "Swim": ":swimmer:",
      "Throw": ":dart:",
      "Track": ":mag_right:",
      "Arabic": ":United_Arab_Emirates:",
      "Bengali": ":Bangladesh:",
      "Chinese": ":China:",
      "Czech": ":Czechia:",
      "Danish": ":Denmark:",
      "Dutch": ":Netherlands:",
      "English": ":United_Kingdom:",
      "Finnish": ":Finland:",
      "French": ":France:",
      "German": ":Germany:",
      "Greek": ":Greece:",
      "Hindi": ":India:",
      "Hungarian": ":Hungary:",
      "Italian": ":Italy:",
      "Japanese": ":Japan:",
      "Korean": ":South_Korea:",
      "Norwegian": ":Norway:",
      "Polish": ":Poland:",
      "Portuguese": ":Portugal:",
      "Romanian": ":Romania:",
      "Russian": ":Russia:",
      "Spanish": ":Spain:",
      "Swedish": ":Sweden:",
      "Turkish": ":Turkey:",
      "Vietnamese": ":Vietnam:",
      "Hebrew": ":Israel:",
      "Thai": ":Thailand:",
      "Swahili": ":Kenya:",
      "Urdu": ":Pakistan:",
      "Malay": ":Malaysia:",
      "Filipino": ":Philippines:",
      "Indonesian": ":Indonesia:",
      "Maltese": ":Malta:",
      "Nepali": ":Nepal:",
      "Slovak": ":Slovakia:",
      "Slovenian": ":Slovenia:",
      "Ukrainian": ":Ukraine:",
      "Bulgarian": ":Bulgaria:",
      "Estonian": ":Estonia:",
      "Icelandic": ":Iceland:",
      "Latvian": ":Latvia:",
      "Lithuanian": ":Lithuania:",
      "Luxembourgish": ":Luxembourg:",
      "Samoan": ":Samoa:",
      "Tongan": ":Tonga:",
      "Fijian": ":Fiji:",
      "Tahitian": ":French_Polynesia:",
      "Hawaiian": ":United_States:",
      "Maori": ":New_Zealand:",
      "Tibetan": ":China:",
      "Kurdish": ":South_Korea:",
      "Pashto": ":Afghanistan:",
      "Dari": ":Afghanistan:",
      "Balinese": ":Indonesia:",
      "Turkmen": ":Turkmenistan:",
      "Bosnian": ":Bosnia_&_Herzegovina:",
      "Croatian": ":Croatia:",
      "Serbian": ":Serbia:",
      "Macedonian": ":North_Macedonia:",
      "Albanian": ":Albania:",
      "Mongolian": ":Mongolia:",
      "Armenian": ":Armenia:",
      "Georgian": ":Georgia:",
      "Azerbaijani": ":Azerbaijan:",
      "Kazakh": ":Kazakhstan:",
      "Kyrgyz": ":Kyrgyzstan:",
      "Tajik": ":Tajikistan:",
      "Uzbek": ":Uzbekistan:",
      "Tatar": ":Russia:",
      "Bashkir": ":Russia:",
      "Chechen": ":Russia:",
      "Belarusian": ":Belarus:",
      "Moldovan": ":Moldova:",
      "Sami": ":Norway:",
      "Faroese": ":Faroe_Islands:",
      "Irish": ":Ireland:",
      "Welsh": ":United_Kingdom:",
      "Scots Gaelic": ":United_Kingdom:",
      "Basque": ":Spain:",
      "Catalan": ":Spain:",
      "Galician": ":Spain:",
      "Yiddish": ":Israel:",
      "Malayalam": ":India:",
      "Tamil": ":India:",
      "Burmese": ":Myanmar_(Burma):",
      "Khmer": ":Cambodia:",
      "Lao": ":Laos:",
      "Bisaya": ":Philippines:",
      "Cebuano": ":Philippines:",
      "Ilocano": ":Philippines:",
      "Hiligaynon": ":Philippines:",
      "Waray": ":Philippines:",
      "Chichewa": ":Malawi:",
      "Kinyarwanda": ":Rwanda:",
      "Swazi": ":Eswatini:",
      "Tigrinya": ":Eritrea:",
      "Haitian Creole": ":Haiti:",
      "Frisian": ":Netherlands:",
      "Esperanto": ":white_flag:",
      "Latin": ":white_flag:",
      "Scots": ":United_Kingdom:",
      "Pirate": ":pirate_flag:",
      "Astronomy":":telescope:",
      "Biology":":microscope:",
      "Botany":":herb:",
      "Chemistry":":test_tube:",
      "Cryptography":":lock:",
      "Engineering":":gear:",
      "Forensics":":mag_right:",
      "Geology":":earth_americas:",
      "Mathematics":":1234:",
      "Meteorology":":cloud_with_lightning_and_rain:",
      "Pharmacy":":pill:",
      "Physics":":atom_symbol:",
      "Weird Science": ":scientist:",
      "Zoology":":paw_prints:",

      # New Explicit Mappings
      "Art / Craft (any)": ":art:",
      "Fighting (Brawl)": ":boxing_glove:",
      "Firearms (Handgun)": ":gun:",
      "Firearms (Rifle/Shotgun)": ":gun:",
      "Language (Other)": ":globe_with_meridians:",
      "Language (Own)": ":speech_balloon:",
      "Pilot (any)": ":airplane:",
      "Science (any)": ":microscope:",
      "Survival (any)": ":camping:",

      # Base Keys for Fuzzy Matching
      "Science": ":microscope:",
      "Fighting": ":boxing_glove:",
      "Firearms": ":gun:",
      "Art / Craft": ":art:",
      "Language": ":globe_with_meridians:",
      "Drive": ":blue_car:",
      "Survival": ":camping:",
      "Pilot": ":airplane:",

      # Era Specific / New Skills
      "Computer Use": ":computer:",
      "Electronics": ":electric_plug:",
      "Alienism": ":brain:",
      "Drive Carriage": ":horse:",
      "Operate Heavy Machinery": ":bullettrain_front:",
      "Reassure": ":handshake:",
      "Religion": ":place_of_worship:",
      "Animal Handling": ":lion_face:",
      "Drive Wagon/Coach": ":horse:",
      "Gambling": ":game_die:",
      "Rope Use": ":knot:",
      "Trap": ":mouse_trap:",
      "Drive (Horses/Oxen)": ":ox:",
      "Insight": ":bulb:",
      "Other Kingdoms (any)": ":world_map:",
      "Kingdom (Own)": ":castle:",
      "Pilot Boat": ":sailboat:",
      "Read/Write Language (any)": ":pencil:",
      "Repair/Devise": ":hammer_and_wrench:",
      "Ride Horse": ":horse_racing:",
      "Status": ":crown:",
      "Natural World (any)": ":deciduous_tree:",
      "Hypnosis": ":face_with_spiral_eyes:",
      "Lore": ":scroll:",
      "Artillery": ":crossed_swords:",

      # Weapons
      "Axe": ":axe:",
      "Sword": ":crossed_swords:",
      "Spear": ":dagger:",
      "Bow": ":bow_and_arrow:",
      "Flamethrower": ":fire:",
      "Heavy Weapons": ":rocket:",
      "Machine Gun": ":gun:",
      "Submachine Gun": ":gun:",
      "Chainsaw": ":axe:",
  }

def get_stat_emoji(stat_name):
  # 1. Exact match
  if stat_name in stat_emojis:
      return stat_emojis[stat_name]

  # 2. Check for "Name (Specialization)" pattern
  match = re.match(r"(.+?) \((.+)\)$", stat_name)
  if match:
      base = match.group(1)
      spec = match.group(2)

      # Try looking up the specialization directly
      if spec in stat_emojis:
           return stat_emojis[spec]

      # Try looking up the base name
      if base in stat_emojis:
           return stat_emojis[base]

  return ":question:"
