occupation_emojis = {
    "Accountant": "🧮",
    "Acrobat": "🤸",
    "Stage Actor": "🎭",
    "Film star": "🌟",
    "Agency detective": "🕵️",
    "Alienist": "🧠",
    "Animal trainer": "🦁",
    "Antiquarian": "🏺",
    "Antique dealer": "🕰️",
    "Archaeologist": "🦴",
    "Architect": "📐",
    "Artist": "🎨",
    "Asylum Attendant": "🏥",
    "Athlete": "🏃",
    "Author": "✍️",
    "Bartender": "🍸",
    "Big Game Hunter": "🤠",
    "Book Dealer": "📚",
    "Bounty Hunter": "🤠",
    "Boxer Wrestler": "🥊",
    "Butler Valet Maid": "🤵",
    "Clergy": "⛪",
    "Computer Programmer Technician Hacker": "💻",
    "Cowboy Girl": "🤠",
    "Craftsperson": "🔨",
    "Criminal": "🎭",
    "Assassin": "🗡️",
    "Bank Robber": "🏦",
    "Bootlegger Thug": "🥃",
    "Burglar": "🏠",
    "Conman": "🃏",
    "Freelance Criminal": "🔫",
    "Gun Moll": "💃",
    "Fence": "💍",
    "Forger Counterfeiter": "💵",
    "Smuggler": "🚤",
    "Street Punk": "🎸",
    "Cult Leader": "🛐",
    "Deprogrammer": "🧠",
    "Designer": "👗",
    "Dilettante": "🍸",
    "Diver": "🤿",
    "Doctor of Medicine": "👨‍⚕️",
    "Drifter": "🚶‍♂️",
    "Chauffeur": "🚗",
    "Driver": "🚚",
    "Taxi driver": "🚕",
    "Editor": "📰",
    "Elected Official": "🗳️",
    "Engineer": "⚙️",
    "Entertainer": "🎤",
    "Explorer": "🧭",
    "Farmer": "🚜",
    "Federal Agent": "🕴️",
    "Firefighter": "🚒",
    "Foreign Correspondent": "🌍",
    "Forensic Surgeon": "💀",
    "Gambler": "🎲",
    "Gangster Boss": "🚬",
    "Gangster Underling": "🔫",
    "Gentleman Lady": "🎩",
    "Hobo": "🚂",
    "Hospital Orderly": "🏥",
    "Investigative Journalist": "🕵️",
    "Reporter": "🎤",
    "Judge": "⚖️",
    "Laboratory Assistant": "🧪",
    "Laborer Unskilled": "🔨",
    "Lumberjack": "🪓",
    "Miner": "⛏️",
    "Lawyer": "⚖️",
    "Librarian": "📚",
    "Mechanic": "🔧",
    "Military Officer": "🎖️",
    "Missionary": "✝️",
    "Mountain Climber": "🧗",
    "Museum Curator": "🏛️",
    "Musician": "🎻",
    "Nurse": "👩‍⚕️",
    "Occultist": "🔮",
    "Outdoorsman Woman": "⛺",
    "Parapsychologist": "👻",
    "Pharmacist": "💊",
    "Photographer": "📷",
    "Photojournalist": "📸",
    "Pilot": "✈️",
    "Aviator": "🛩️",
    "Police Detective": "👮",
    "Uniformed Police Officer": "👮‍♂️",
    "Private Investigator": "🕵️‍♂️",
    "Professor": "👨‍🏫",
    "Prospector": "⛏️",
    "Prostitute": "💋",
    "Psychiatrist": "🛋️",
    "Psychologist": "🧠",
    "Researcher": "🔬",
    "Sailor Naval": "⚓",
    "Sailor Commercial": "🚢",
    "Salesperson": "🤝",
    "Scientist": "🧪",
    "Secretary": "⌨️",
    "Shopkeeper": "🏪",
    "Soldier Marine": "🪖",
    "Spy": "🕵️",
    "Student Intern": "🎒",
    "Stuntman": "🎬",
    "Tribe Member": "🏹",
    "Undertaker": "⚰️",
    "Union Activist": "📢",
    "Waitress Waiter": "🍽️",
    "Clerk Executive": "👔",
    "Middle Senior Manager": "📈",
    "Zealot": "🚩",
    "Zookeeper": "🦁"
}

def get_occupation_emoji(occupation_name):
    return occupation_emojis.get(occupation_name, "❓")
